/*
    paramedic is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    paramedic is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with paramedic.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.18.1

#include <stan/model/model_header.hpp>

namespace model_variable_efficiency_centered_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_variable_efficiency_centered");
    reader.add_event(37, 35, "end", "model_variable_efficiency_centered");
    return reader;
}

#include <meta_header.hpp>
 class model_variable_efficiency_centered : public prob_grad {
private:
    int N;
    int q_obs;
    int q;
    vector<vector<int> > V;
    vector<vector<int> > W;
public:
    model_variable_efficiency_centered(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_variable_efficiency_centered(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_variable_efficiency_centered_namespace::model_variable_efficiency_centered";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "q_obs", "int", context__.to_vec());
            q_obs = int(0);
            vals_i__ = context__.vals_i("q_obs");
            pos__ = 0;
            q_obs = vals_i__[pos__++];
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "q", "int", context__.to_vec());
            q = int(0);
            vals_i__ = context__.vals_i("q");
            pos__ = 0;
            q = vals_i__[pos__++];
            current_statement_begin__ = 5;
            validate_non_negative_index("V", "N", N);
            validate_non_negative_index("V", "q_obs", q_obs);
            context__.validate_dims("data initialization", "V", "int", context__.to_vec(N,q_obs));
            validate_non_negative_index("V", "N", N);
            validate_non_negative_index("V", "q_obs", q_obs);
            V = std::vector<std::vector<int> >(N,std::vector<int>(q_obs,int(0)));
            vals_i__ = context__.vals_i("V");
            pos__ = 0;
            size_t V_limit_1__ = q_obs;
            for (size_t i_1__ = 0; i_1__ < V_limit_1__; ++i_1__) {
                size_t V_limit_0__ = N;
                for (size_t i_0__ = 0; i_0__ < V_limit_0__; ++i_0__) {
                    V[i_0__][i_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 6;
            validate_non_negative_index("W", "N", N);
            validate_non_negative_index("W", "q", q);
            context__.validate_dims("data initialization", "W", "int", context__.to_vec(N,q));
            validate_non_negative_index("W", "N", N);
            validate_non_negative_index("W", "q", q);
            W = std::vector<std::vector<int> >(N,std::vector<int>(q,int(0)));
            vals_i__ = context__.vals_i("W");
            pos__ = 0;
            size_t W_limit_1__ = q;
            for (size_t i_1__ = 0; i_1__ < W_limit_1__; ++i_1__) {
                size_t W_limit_0__ = N;
                for (size_t i_0__ = 0; i_0__ < W_limit_0__; ++i_0__) {
                    W[i_0__][i_1__] = vals_i__[pos__++];
                }
            }

            // validate, data variables
            current_statement_begin__ = 2;
            check_greater_or_equal(function__,"N",N,0);
            current_statement_begin__ = 3;
            check_greater_or_equal(function__,"q_obs",q_obs,0);
            current_statement_begin__ = 4;
            check_greater_or_equal(function__,"q",q,0);
            current_statement_begin__ = 5;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                for (int k1__ = 0; k1__ < q_obs; ++k1__) {
                    check_greater_or_equal(function__,"V[k0__][k1__]",V[k0__][k1__],0);
                }
            }
            current_statement_begin__ = 6;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                for (int k1__ = 0; k1__ < q; ++k1__) {
                    check_greater_or_equal(function__,"W[k0__][k1__]",W[k0__][k1__],0);
                }
            }
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 9;
            validate_non_negative_index("log_mu", "q", q);
            validate_non_negative_index("log_mu", "N", N);
            num_params_r__ += q * N;
            current_statement_begin__ = 10;
            validate_non_negative_index("beta", "q", q);
            num_params_r__ += q;
            current_statement_begin__ = 11;
        validate_non_negative_index("Sigma", "q", q);
            num_params_r__ += q;
            current_statement_begin__ = 12;
            validate_non_negative_index("e", "q", q);
            num_params_r__ += q;
            current_statement_begin__ = 13;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_variable_efficiency_centered() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("log_mu")))
            throw std::runtime_error("variable log_mu missing");
        vals_r__ = context__.vals_r("log_mu");
        pos__ = 0U;
        validate_non_negative_index("log_mu", "N", N);
        validate_non_negative_index("log_mu", "q", q);
        context__.validate_dims("initialization", "log_mu", "vector_d", context__.to_vec(N,q));
        std::vector<vector_d> log_mu(N,vector_d(static_cast<Eigen::VectorXd::Index>(q)));
        for (int j1__ = 0U; j1__ < q; ++j1__)
            for (int i0__ = 0U; i0__ < N; ++i0__)
                log_mu[i0__](j1__) = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < N; ++i0__)
            try {
            writer__.vector_unconstrain(log_mu[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable log_mu: ") + e.what());
        }

        if (!(context__.contains_r("beta")))
            throw std::runtime_error("variable beta missing");
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "q", q);
        context__.validate_dims("initialization", "beta", "vector_d", context__.to_vec(q));
        vector_d beta(static_cast<Eigen::VectorXd::Index>(q));
        for (int j1__ = 0U; j1__ < q; ++j1__)
            beta(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(beta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable beta: ") + e.what());
        }

        if (!(context__.contains_r("Sigma")))
            throw std::runtime_error("variable Sigma missing");
        vals_r__ = context__.vals_r("Sigma");
        pos__ = 0U;
        validate_non_negative_index("Sigma", "q", q);
        context__.validate_dims("initialization", "Sigma", "row_vector_d", context__.to_vec(q));
        row_vector_d Sigma(static_cast<Eigen::VectorXd::Index>(q));
        for (int j1__ = 0U; j1__ < q; ++j1__)
            Sigma(j1__) = vals_r__[pos__++];
        try {
            writer__.row_vector_lb_unconstrain(0,Sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable Sigma: ") + e.what());
        }

        if (!(context__.contains_r("e")))
            throw std::runtime_error("variable e missing");
        vals_r__ = context__.vals_r("e");
        pos__ = 0U;
        validate_non_negative_index("e", "q", q);
        context__.validate_dims("initialization", "e", "vector_d", context__.to_vec(q));
        vector_d e(static_cast<Eigen::VectorXd::Index>(q));
        for (int j1__ = 0U; j1__ < q; ++j1__)
            e(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,e);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable e: ") + e.what());
        }

        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > log_mu;
            size_t dim_log_mu_0__ = N;
            log_mu.reserve(dim_log_mu_0__);
            for (size_t k_0__ = 0; k_0__ < dim_log_mu_0__; ++k_0__) {
                if (jacobian__)
                    log_mu.push_back(in__.vector_constrain(q,lp__));
                else
                    log_mu.push_back(in__.vector_constrain(q));
            }

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.vector_constrain(q,lp__);
            else
                beta = in__.vector_constrain(q);

            Eigen::Matrix<local_scalar_t__,1,Eigen::Dynamic>  Sigma;
            (void) Sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                Sigma = in__.row_vector_lb_constrain(0,q,lp__);
            else
                Sigma = in__.row_vector_lb_constrain(0,q);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  e;
            (void) e;  // dummy to suppress unused var warning
            if (jacobian__)
                e = in__.vector_lb_constrain(0,q,lp__);
            else
                e = in__.vector_lb_constrain(0,q);

            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0,lp__);
            else
                sigma = in__.scalar_lb_constrain(0);


            // transformed parameters
            current_statement_begin__ = 16;
            validate_non_negative_index("mu", "q", q);
            validate_non_negative_index("mu", "N", N);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > mu(N, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(q))));
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu,DUMMY_VAR__);
            current_statement_begin__ = 17;
            validate_non_negative_index("p", "q", q);
            validate_non_negative_index("p", "N", N);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > p(N, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(q))));
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p,DUMMY_VAR__);


            current_statement_begin__ = 18;
            stan::math::assign(mu, stan::math::exp(log_mu));
            current_statement_begin__ = 19;
            for (int j = 1; j <= N; ++j) {

                current_statement_begin__ = 20;
                stan::model::assign(p, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            divide(elt_multiply(e,get_base1(mu,j,"mu",1)),sum(elt_multiply(e,get_base1(mu,j,"mu",1)))), 
                            "assigning variable p");
            }

            // validate transformed parameters
            for (int i0__ = 0; i0__ < N; ++i0__) {
                for (int i1__ = 0; i1__ < q; ++i1__) {
                    if (stan::math::is_uninitialized(mu[i0__](i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: mu" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }
            for (int i0__ = 0; i0__ < N; ++i0__) {
                for (int i1__ = 0; i1__ < q; ++i1__) {
                    if (stan::math::is_uninitialized(p[i0__](i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: p" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 16;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"mu[k0__]",mu[k0__],0);
            }
            current_statement_begin__ = 17;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"p[k0__]",p[k0__],0);
            }

            // model body

            current_statement_begin__ = 24;
            lp_accum__.add(normal_log<propto__>(beta, 0, stan::math::sqrt(50.0)));
            current_statement_begin__ = 25;
            lp_accum__.add(lognormal_log<propto__>(Sigma, 0, stan::math::sqrt(50.0)));
            current_statement_begin__ = 27;
            lp_accum__.add(inv_gamma_log<propto__>(sigma, 2, 1));
            current_statement_begin__ = 28;
            lp_accum__.add(lognormal_log<propto__>(e, 0, stan::math::sqrt(sigma)));
            current_statement_begin__ = 30;
            for (int j = 1; j <= N; ++j) {

                current_statement_begin__ = 31;
                lp_accum__.add(normal_log<propto__>(get_base1(log_mu,j,"log_mu",1), beta, Sigma));
                current_statement_begin__ = 32;
                lp_accum__.add(poisson_log<propto__>(get_base1(V,j,"V",1), stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_min_max(1, q_obs), stan::model::nil_index_list())), "mu")));
                current_statement_begin__ = 33;
                lp_accum__.add(multinomial_log<propto__>(get_base1(W,j,"W",1), get_base1(p,j,"p",1)));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("log_mu");
        names__.push_back("beta");
        names__.push_back("Sigma");
        names__.push_back("e");
        names__.push_back("sigma");
        names__.push_back("mu");
        names__.push_back("p");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(q);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "model_variable_efficiency_centered_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector<vector_d> log_mu;
        size_t dim_log_mu_0__ = N;
        for (size_t k_0__ = 0; k_0__ < dim_log_mu_0__; ++k_0__) {
            log_mu.push_back(in__.vector_constrain(q));
        }
        vector_d beta = in__.vector_constrain(q);
        row_vector_d Sigma = in__.row_vector_lb_constrain(0,q);
        vector_d e = in__.vector_lb_constrain(0,q);
        double sigma = in__.scalar_lb_constrain(0);
            for (int k_1__ = 0; k_1__ < q; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(log_mu[k_0__][k_1__]);
                }
            }
            for (int k_0__ = 0; k_0__ < q; ++k_0__) {
            vars__.push_back(beta[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < q; ++k_0__) {
            vars__.push_back(Sigma[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < q; ++k_0__) {
            vars__.push_back(e[k_0__]);
            }
        vars__.push_back(sigma);

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 16;
            validate_non_negative_index("mu", "q", q);
            validate_non_negative_index("mu", "N", N);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > mu(N, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(q))));
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu,DUMMY_VAR__);
            current_statement_begin__ = 17;
            validate_non_negative_index("p", "q", q);
            validate_non_negative_index("p", "N", N);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > p(N, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(q))));
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p,DUMMY_VAR__);


            current_statement_begin__ = 18;
            stan::math::assign(mu, stan::math::exp(log_mu));
            current_statement_begin__ = 19;
            for (int j = 1; j <= N; ++j) {

                current_statement_begin__ = 20;
                stan::model::assign(p, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            divide(elt_multiply(e,get_base1(mu,j,"mu",1)),sum(elt_multiply(e,get_base1(mu,j,"mu",1)))), 
                            "assigning variable p");
            }

            // validate transformed parameters
            current_statement_begin__ = 16;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"mu[k0__]",mu[k0__],0);
            }
            current_statement_begin__ = 17;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"p[k0__]",p[k0__],0);
            }

            // write transformed parameters
            if (include_tparams__) {
            for (int k_1__ = 0; k_1__ < q; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(mu[k_0__][k_1__]);
                }
            }
            for (int k_1__ = 0; k_1__ < q; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(p[k_0__][k_1__]);
                }
            }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_variable_efficiency_centered";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "log_mu" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Sigma" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "mu" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "log_mu" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Sigma" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= q; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "mu" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            for (int k_1__ = 1; k_1__ <= q; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef model_variable_efficiency_centered_namespace::model_variable_efficiency_centered stan_model;


#endif
